apply plugin: 'maven-publish'
apply plugin: 'signing'

tasks.register('androidJavadocs', Javadoc) {
    source = android.sourceSets.main.java.sourceFiles
    classpath += project.files(android.getBootClasspath())
}

tasks.register('androidJavadocsJar', Jar) {
    archiveClassifier.set("javadoc")
    from tasks.named('androidJavadocs').get().destinationDir
}

tasks.register('androidSourcesJar', Jar) {
    archiveClassifier.set("sources")
    from android.sourceSets.main.java.sourceFiles
}

publishing {
    publications {
        maven(MavenPublication) {
            afterEvaluate { project ->
                def releaseComponent = components.findByName('release')
                if (releaseComponent) {
                    from releaseComponent
                }
                artifact tasks.named('androidSourcesJar').get()
                artifact tasks.named('androidJavadocsJar').get()
                version = project.version
            }

            pom {
                name = POM_NAME
                packaging = POM_PACKAGING
                description = POM_DESCRIPTION
                url = POM_URL
                scm {
                    url = POM_SCM_URL
                    connection = POM_SCM_CONNECTION
                    developerConnection = POM_SCM_DEV_CONNECTION
                }

                licenses {
                    license {
                        name = POM_LICENCE_NAME
                        url = POM_LICENCE_URL
                        distribution = POM_LICENCE_DIST
                    }
                }

                developers {
                    developer {
                        id = POM_DEVELOPER_ID
                        name = POM_DEVELOPER_NAME
                    }
                }
            }
        }
    }
}

signing {
    required { isReleaseBuild() && gradle.taskGraph.hasTask("publishing") }
    def signingInMemoryKey = findProperty('signingInMemoryKey')
    def signingInMemoryKeyPassword = findProperty('signingInMemoryKeyPassword') ?: ''
    if (signingInMemoryKey) {
        useInMemoryPgpKeys(signingInMemoryKey, signingInMemoryKeyPassword)
    }
    sign publishing.publications.maven
}
