/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yalantis_ucrop_UCropActivity */

#ifndef _Included_com_yalantis_ucrop_UCropActivity
#define _Included_com_yalantis_ucrop_UCropActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_yalantis_ucrop_UCropActivity_DEFAULT_COMPRESS_QUALITY
#define com_yalantis_ucrop_UCropActivity_DEFAULT_COMPRESS_QUALITY 90L
#undef com_yalantis_ucrop_UCropActivity_NONE
#define com_yalantis_ucrop_UCropActivity_NONE 0L
#undef com_yalantis_ucrop_UCropActivity_SCALE
#define com_yalantis_ucrop_UCropActivity_SCALE 1L
#undef com_yalantis_ucrop_UCropActivity_ROTATE
#define com_yalantis_ucrop_UCropActivity_ROTATE 2L
#undef com_yalantis_ucrop_UCropActivity_ALL
#define com_yalantis_ucrop_UCropActivity_ALL 3L
#undef com_yalantis_ucrop_UCropActivity_TABS_COUNT
#define com_yalantis_ucrop_UCropActivity_TABS_COUNT 3L
#undef com_yalantis_ucrop_UCropActivity_SCALE_WIDGET_SENSITIVITY_COEFFICIENT
#define com_yalantis_ucrop_UCropActivity_SCALE_WIDGET_SENSITIVITY_COEFFICIENT 15000L
#undef com_yalantis_ucrop_UCropActivity_ROTATE_WIDGET_SENSITIVITY_COEFFICIENT
#define com_yalantis_ucrop_UCropActivity_ROTATE_WIDGET_SENSITIVITY_COEFFICIENT 42L
/*
 * Class:     com_yalantis_ucrop_UCropActivity
 * Method:    omfgCpp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yalantis_ucrop_UCropActivity_omfgCpp
  (JNIEnv *, jobject);

/*
 * Class:     com_yalantis_ucrop_UCropActivity
 * Method:    cropFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;FF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yalantis_ucrop_UCropActivity_cropFile
  (JNIEnv *, jobject, jstring, jstring, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
