/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yalantis_ucrop_view_CropImageView */

#ifndef _Included_com_yalantis_ucrop_view_CropImageView
#define _Included_com_yalantis_ucrop_view_CropImageView
#ifdef __cplusplus
extern "C" {
#endif
#undef com_yalantis_ucrop_view_CropImageView_RECT_CORNER_POINTS_COORDS
#define com_yalantis_ucrop_view_CropImageView_RECT_CORNER_POINTS_COORDS 8L
#undef com_yalantis_ucrop_view_CropImageView_RECT_CENTER_POINT_COORDS
#define com_yalantis_ucrop_view_CropImageView_RECT_CENTER_POINT_COORDS 2L
#undef com_yalantis_ucrop_view_CropImageView_MATRIX_VALUES_COUNT
#define com_yalantis_ucrop_view_CropImageView_MATRIX_VALUES_COUNT 9L
#undef com_yalantis_ucrop_view_CropImageView_DEFAULT_MAX_BITMAP_SIZE
#define com_yalantis_ucrop_view_CropImageView_DEFAULT_MAX_BITMAP_SIZE 0L
#undef com_yalantis_ucrop_view_CropImageView_DEFAULT_IMAGE_TO_CROP_BOUNDS_ANIM_DURATION
#define com_yalantis_ucrop_view_CropImageView_DEFAULT_IMAGE_TO_CROP_BOUNDS_ANIM_DURATION 500L
#undef com_yalantis_ucrop_view_CropImageView_DEFAULT_MAX_SCALE_MULTIPLIER
#define com_yalantis_ucrop_view_CropImageView_DEFAULT_MAX_SCALE_MULTIPLIER 10.0f
#undef com_yalantis_ucrop_view_CropImageView_SOURCE_IMAGE_ASPECT_RATIO
#define com_yalantis_ucrop_view_CropImageView_SOURCE_IMAGE_ASPECT_RATIO 0.0f
#undef com_yalantis_ucrop_view_CropImageView_DEFAULT_ASPECT_RATIO
#define com_yalantis_ucrop_view_CropImageView_DEFAULT_ASPECT_RATIO 0.0f

/*
 * Class:     com_yalantis_ucrop_view_CropImageView
 * Method:    cropFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIIIF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yalantis_ucrop_view_CropImageView_cropFileOpenCV
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint, jfloat);

/*
* Class:     com_yalantis_ucrop_view_CropImageView
* Method:    cropFile
* Signature: (Ljava/lang/String;Ljava/lang/String;IIIIF)Z
*/
JNIEXPORT jboolean JNICALL Java_com_yalantis_ucrop_view_CropImageView_cropFileCImg
(JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
