/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yalantis_ucrop_UCropActivity_GestureTypes */

#ifndef _Included_com_yalantis_ucrop_UCropActivity_GestureTypes
#define _Included_com_yalantis_ucrop_UCropActivity_GestureTypes
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
