/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yalantis_ucrop_view_CropImageView_CropBoundsChangeListener */

#ifndef _Included_com_yalantis_ucrop_view_CropImageView_CropBoundsChangeListener
#define _Included_com_yalantis_ucrop_view_CropImageView_CropBoundsChangeListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
