apply plugin: 'com.android.library'
apply from: '../mavenpush.gradle'

android {
    compileSdk 36
    namespace = "com.yalantis.ucrop"
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 36
        versionCode 27
        versionName "2.2.12-native"

        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        buildConfig true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    resourcePrefix 'ucrop_'

    sourceSets.main {
        jni.srcDirs = []
    }
    lint {
        abortOnError false
    }

}

dependencies {
    implementation "androidx.appcompat:appcompat:${androidx_appcompat_version}"
    implementation "androidx.exifinterface:exifinterface:${androidx_exifinterface_version}"
    implementation "androidx.transition:transition:${androidx_transition_version}"
    implementation "com.squareup.okhttp3:okhttp:${okhttp_version}"
}
